title: Nexus Server Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://gracious-lamport-d8d2a8.netlify.app/
params:
  disableDarkMode: false
  shortDateFormat: 15:04 â€” Jan 2
  down: "#e60000"
  systems:
    - name: Dashboard
      category: Nexus Server
    - name: Jellyfin
      category: Nexus Server
    - name: Ombi
      description: ""
      category: Nexus Server
    - name: Account Management
      category: Nexus Server
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Nexus Server
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
